- data/finaid.md
This PR fixes the typos and spacing errors on finaid.md
> fix typos in finaid.md

- data/covid-info.md
> add covid info page

- data/finaid.md
- data/mentorship.md
- data/tickets.md
Please check and take anything I contribute with a pinch of salt.
I have tried to:
* Update tone of voice to be friendly but serious.
* Corrected typos.
* Simplified language so it's clearer for non-native speakers.
* Clarified points (please check).
* Removed duplications.
All feedback most gratefully received.
> Copy edits and corrections for finaid, mentorship and tickets.

- data/finaid.md
- data/tickets.md
put buy-ticket button up top too just in case people know the drill and want to go to the shop directly.
> put buy-ticket button up top too

- data/finaid.md
> Fix typo €300 to €400

- components/header.tsx
- components/nav-items.tsx
- data/links.json
- styles/main.css
You can add sublinks by adding items to links, see where in the json below
```
{
"header": [
{
"name": "Finaid",
"path": "/finaid"
},
{
"name": "FAQ",
"path": "/faq"
},
{
"name": "Sponsor",
"path": "/sponsor"
},
{
"name": "Where",
"path": "/where",
"items": [
{
"name": "Campus",
"path": "/campus"
}
]
},
{
"name": "Visa Info",
"path": "/visa"
},
{
"name": "Code of Conduct",
"path": "https://www.europython-society.org/coc/"
}
],
"footer": [
{
"name": "CFP",
"path": "/cfp"
},
{
"name": "Community Voting",
"path": "/voting"
},
{
"name": "Mentorship",
"path": "/mentorship"
},
{
"name": "FAQ",
"path": "/faq"
},
{
"name": "Covid Info",
"path": "/covid-info"
},
{
"name": "Sponsor",
"path": "/sponsor"
},
{
"name": "Contacts",
"path": "/contacts"
},
{
"name": "Terms",
"path": "/terms"
},
{
"name": …
```
> CSS Update

- data/pages-content/faq.md
Fixing issue https://github.com/EuroPython/website/issues/97
> Add incomplete Finaid info on FAQ

- pages/session/[slug].tsx
- styles/main.css
> Add sessions in parallel, next sessions and more info about the session

- components/header.tsx
- styles/main.css
> Fix header mobile

- components/schedule/schedule.tsx
- styles/main.css
Add a end of day break at the end:
> Add end of day

- pages/schedule/[day].tsx
> Add back to top link

- components/ical-link.tsx
- components/schedule/schedule-utils.ts
- components/schedule/session.tsx
- components/schedule/types.ts
- package-lock.json
- package.json
- pages/schedule/[day].tsx
- styles/main.css
> Add basic ical support

- data/links.json
> add link to sprints

- data/pages-content/sprints.md
> Added Mu to sprints.

- components/schedule/session.tsx
- pages/session/[slug].tsx
- styles/main.css
> Add id of talk in links

- data/pages-content/social-event.md
> added blurb about the musicians

- data/pages-content/sprints.md
Hi EP 2022 webmasters... Submitting `pup` sprint information.
Thanks! :-)
> Adding `pup` sprint info!

- data/live.json
Do not merge until Wednesday evening
> Thursday streams

- data/pages-content/sprints.md
Announcing the `scikit-learn` sprint for EuroPython 2022
> SPRINT: add scikit-learn sprint

- pages/speaker/[slug].tsx
> Add case for missing http in speaker URLs

- data/pages-content/mentorship.md
Simple update on the datetime of the "Ask me Anything for the CfP" event.
> Update datetime for AMA CfP event

- components/clacks.tsx
An oversight on my part when originally suggested. Russel is another deceased EuroPython member.
> Add Russel Winder to clacks

- data/pages-content/visa.md
Pre-ticket sale, form not published.
> Add visa page

- data/pages-content/cfp.md
Simply updates the section about mentorship inside the CfP page.
> Update first time speaker section of cfp page

- data/links.json
- data/pages-content/voting.md
If the placeholder page is needed before community voting, it can be merged.
> Voting page before release

- data/sponsors.json
I'm adding the EPS as a Financial Aid sponsor
> Add EPS to sponsors.json

- data/pages-content/faq.md
- data/pages-content/mentorship.md
Updates the date and time of the first time speaker's workshop
> Update mentorship page

- data/pages-content/sprints.md
Add details for BeeWare as a sprint participant.
> Add BeeWare sprint details

- data/pages-content/sprints.md
Here is our Sprint proposal for Europython 2023
> Update sprints.md with WitnessAngel sprint

- data/pages-content/faq.md
- data/pages-content/mentorship.md
SImple update of mentorship page after the first time speaker's workshop
> Update mentorship content

- data/links.json
- data/pages-content/volunteers.md
Updates content on the volunteers page including:
- Updated form link
- Information about free conference ticket (8+ hours)
- Updated volunteering activities
> Update Volunteers page

- data/pages-content/mentored-sprint.md
- data/pages-content/sprints.md
Proposes an sktime sprint and mentored sprint. We will be at EuroPython 2023 with at least 2 developers.
> sktime sprint

- data/pages-content/sprints.md
Lance is a new columnar format for multi-modal AI and billion scale vector search. It's 2000x faster than parquet for random access, comes with a scalable vector index, and is used as the storage layer for petabyte scale unstructured data lakes
> Proposed sprint for Lance/LanceDB

- data/links.json
- data/pages-content/accessibility.md
- data/pages-content/faq.md
Copied the contents from google doc to this page, this is not linked anywhere though, so someone from the team can find out where best to link the a11y page.
> Adding accessibility page

- data/pages-content/accessibility.md
Forgot to mention where I pulled a11y info from in the page. It's taken from the google doc.
> Added attributions from where we got some of the a11y information from

- data/pages-content/accessibility.md
Fix minor typos/grammar in accessibility.md
> Fix minor typos/grammar in accessibility.md

- data/pages-content/accessibility.md
Lift is hard to find on the ground floor for folks who need it to go to first floor registration and we don't have anyone to guide folks in the right direction.
This update with directions and photos (thanks to Cyril) to help people find the lift on the ground floor at PCC.
> PCC lift directions

- data/pages-content/sprints.md
Small update to sprints page about times, food and coffee.
> updated start and end times; also mentioned lunch and coffee is provided

- data/pages-content/sprints.md
Not sure if this is too late, but I will try anyway :)
> Add sprint for the Patito library

- data/pages-content/sprints.md
Even later than @JakobGM apparently :upside_down_face: 
Happy to rebase once #391 is in.
> Add qutebrowser sprint

- data/pages-content/sprints.md
Room change for BeeWare sprint
cc @freakboy3742
> Bees are buzzing to RB 109 🐝

- data/pages-content/sprints.md
Address https://github.com/EuroPython/website/issues/400 by removing emails.
> Remove emails

- data/home/intro.md
This PR simply fixes a typo in the `data/home/intro.md`
N/A
> Fix intro typo

- data/links.json
- data/pages-content/faq.md
- data/pages-content/visa.md
Simply adds `faq` and `visa` page with some basic content. Feel free to contribute especially for the `faq` page.
> Add visa and faq info

- data/links.json
- data/pages-content/finaid.md
- pnpm-lock.yaml
> Adapt finaid content from 2023 for 2024

- components/header/header.tsx
- data/links.json
- pnpm-lock.yaml
addressing https://github.com/EuroPython/website/issues/461
> Mobile menu on

- data/links.json
- data/pages-content/cfp.md
This includes all the information from 2023
adapted to the 2024 version.
> Add CfP page

- data/pages-content/faq.md
> Fix EP2023 schedule link

- .github/workflows/chromatic.yml
- package.json
Chromatic deployment started to fail on the recent upgrade: https://github.com/EuroPython/website/actions/runs/7965387109/job/21745251681
I'm aligning CI with Chromatic [doc](https://www.chromatic.com/docs/github-actions/) with a hope that it will work.
> Fix chromatic CI

- data/home/intro.md
Adding helpdesk@europython.eu to the home page
> Update intro page

- data/pages-content/mentorship.md
This PR will update the mentorship page after some deadlines have passed (One-on-One Mentorship & The Ask Me Anything for the CfP ones).
> [DO NOT MERGE] Update mentorship page

- data/pages-content/mentorship.md
This PR simply updates the `mentorship.md` by adding the Ask me Anything for the CfP session YT recording link.
> Add recording for AMA session

- data/pages-content/cfp.md
Adding 7 more days for the cfp extension.
> cfp: update deadline date

- data/pages-content/finaid.md
Simply fixes the logo of EPS in the finaid page
> Fix eps logo on finaid page

- components/header/header.tsx
It wasn't easy to go back to home page otherwise :)
> revive header logo to return home

- data/pages-content/cfp.md
Reverts EuroPython/website#494
> Revert "Add a note that cfp is down at the moment"

- src/content/pages/faq.mdx
Simply adds a dedicated section for COVID questions into the FAQ page.
Fixes https://github.com/EuroPython/website/issues/503
> Add covid related FAQ

- src/content/pages/faq.mdx
Simply updates the FAQ with new questions and reviews the existing ones.
WIP: There are some milestones we need to set before merging.
> WIP: Update FAQ

- .astro/types.d.ts
- src/content/pages/voting.mdx
- src/data/links.json
> Add Community Voting page

- astro.config.mjs
- src/components/prose/prose.astro
- src/styles/global.css
> Mobile font fixes

- .astro/types.d.ts
- .dockerignore
- .gitignore
- Dockerfile
- README.md
- docker-compose.yml
- src/components/sponsor-tiers/sponsor-tiers.tsx
- src/content/pages/faq.mdx
- src/content/pages/finaid.mdx
- src/content/pages/sponsor.mdx
- src/content/pages/sponsor/information.mdx
- src/data/links.json
- src/pages/[...slug].astro
- add sponsor page for 2024
- change link from finaid from email to sponsor page
- add docker dev env option
> add sponsor page for ep2024

- src/content/pages/where.mdx
Proposing changing this as Lítačka is not exactly that well-known by foreigners, and makes it way easier to purchase tickets.
> Change public transport phone app to Lítačka

- src/content/pages/visa.mdx
Updates the content of the visa page
> Update visa page

- src/components/sponsor-tiers/sponsor-tiers.tsx
- src/content/pages/sponsor.mdx
- src/styles/global.css
- Fix the ribbon covering the text (a better looking solution would be nice instead of this fix)
- Fix buttons sticking too close
closes #534
> Fix sponsor page for mobile view

- src/content/pages/faq.mdx
- Move "Ticket Sales Start" to done
- Since the ticket sales are open now, update the text accordingly
> Update FAQ page

- src/content/pages/mentorship.mdx
Simply updates the mentorship page with the date of the event
> Add first-time speaker's workshop date

- src/content/pages/tickets.mdx
This PR simply uncomments the section of the volume discounts
> Uncomment part of the volume discounts

- src/content/pages/faq.mdx
Changed the reference from last years programme to point to the current  (incomplete) session list. I hope i got the syntax for the link correct.
(And removed the part with the community vote as this is in the past for 2024)
> Updated the programme question to point to the current list of sessions.

- src/content/pages/faq.mdx
As the question arose I added a paragraph containing the message about
* Light lunch
* coffee breaks
* mention of the social event at one of the evenings.
> Added  a short section about food (including social event) at the con

- src/content/pages/volunteers.mdx
- src/data/links.json
Updated to current information on volunteering.
- Link points to volunteers helpdesk as the form is waiting for the finalized perks
- All references to vouchers for volunteering have been removed as this needs clarification.
> Updated copy of the 2023 volunteer page.

- src/content/pages/keynoters.mdx
- src/data/links.json
- src/pages/keynoters.astro
Feel free to close this. Just a temporary fix from someone who doesn't know Astro :)
fixes #611
> fix keynoters 404

- src/content/pages/faq.mdx
- src/content/pages/finaid.mdx
- Updated some dates
- Added volunteers page link to "how to help" section
> Update FAQ and finaid pages

- src/data/links.json
> Add accessibility page to navbar links

- src/content/pages/wasm.mdx
- src/data/links.json
Hi folks :wave: 
I've added the blurb for the WASM summit via the page created in this PR.
~~**TODO**: Someone (who?) will need to add this page to the menu system so it's easy to find from the top level menu.~~
Happy to change anything or adjust according to feedback. It's basically a cut and paste of last year's page. :wink:
> Add page about WASM summit.

- src/content/deadlines/03_volunteering.mdx
As the finaid deadline has passed, we can add a card for the new page regarding onsite volunteers.
Added [DO NOT MERGE] label as I think it needs to be approved from ops <3
> Add volunteering card

- src/pages/speaker/[slug].astro
> Adjust spacing in speaker pages

- src/pages/session/[slug].astro
> Don't render speakers section if there are no speakers in a session page

- src/data/links.json
- src/pages/speakers.astro
Similar to last year
<details>
<summary>Quick preview images</summary>
</details>
> Add speakers page

- src/pages/session/[slug].astro
Is a suggestion from @artcz
Closes #635
> Add session type and track to session pages

- src/components/sessions/list-sessions.astro
This fixes the session listing
> Rename submission_type to session_type in list-sessions component

- src/content/config.ts
- src/pages/session/[slug].astro
Closes #375 
Looks like this: [(session shown in example)](https://ep2024-njl6al6ic-europython-society.vercel.app/session/are-llms-smarter-in-some-languages-than-others)
> Add session resources to session pages

- src/content/pages/humble-data.mdx
- src/data/links.json
Text for the Humble Data workshop at Europython 2024.
Original author was Jodie Burchell.
Authored-by: Jodie Burchell
> Add Humble Data as an event

- src/pages/schedule/[day].astro
> Use same row number when a slot is a room change before a break

- src/components/sessions/filter.astro
- src/components/sessions/list-sessions.astro
- src/components/tag/tag.tsx
Closes #634
The changes on filter.astro is to be able to accept filters from URL parameters.
The changes on tag.tsx is to be able to pass a link.
Fancy hover style: (it turns blue)
Better mobile view:
> Insert links to tags, add some style :), fix mobile view for tags

- src/components/header/header.astro
- src/data/links.json
- src/pages/schedule.astro
Finds the closest date and redirects to that day's schedule page.
> Schedule redirects

- src/content/pages/mentorship.mdx
Adds the first time speaker's workshop recording link to the mentorship page
> Update mentorship workshop

- src/pages/schedule/[day].astro
> Fix z-index

- src/components/schedule/session.astro
- src/pages/schedule/[day].astro
> Improve tab order on schedule

- src/content/pages/finaid.mdx
Adds information about the grant for remote tickets.
[DO NOT MERGE] prefix added as it requires review from @alessiamarcolini
> Add remote finaid information

- src/content/pages/speakers-dinner.mdx
Suggestion to add the speakers dinner menu on the website.
Let me know what do you think: @laisbsc @clytaemnestra
> Suggestion: Add speakers dinner menu

- src/content/pages/programme.mdx
- Pyladies lunch 
- Community Organiser's Lunch
- Boat Cruise
- PyBurger
> Add missing events to /programme

- src/components/schedule/session.astro
- src/components/schedule/speakers.astro
> Add links to speakers

- src/pages/session/[slug].astro
> Use prose to make title scale based on device width

- src/content/pages/explore.mdx
- Added some links, and further tightened up some minor spelling/grammar problems. 
-  merged art and culture, moved some music options from art to music. 
- Moved music and clubbing to after art and culture. 
- Now food and drinks is a separate section.
- Added sports and outdoors section.
- Removed Prague roof festival as it is not running during conf.
- Removed Jazz Festival Mladí ladí jazz, as it starts in September.
> Explore page small fixes

- src/components/schedule/session.astro
> Show room name

- astro.config.mjs
- vercel.json
Looks like this is not officially supported by Astro, but might work
> Add redirect for discord

- src/content/pages/social-event.mdx
> Changed ticket information for social event to sale open.

- src/content/pages/where.mdx
Fixing link: convenient orientation guide (PDF)
> Fix broken link in where page

- src/content/pages/sprints.mdx
We would love to organize a Sprint. We had one in PyCon US just before the pandemic, and it was a great experience!
> Propose a EuroPython2024 Sprint on Falcon framework

- src/content/pages/accessibility.mdx
I went through PCC and realized we can do this better. One bag went to the low-stim room, the other will have more use at the Info desk. CC @thepetk, @anezkamll
> Update the information about the neurodiversity items available

- src/data/home/venue.mdx
@cmaureir @cybit  please review & merge
> Fix homepage sprints venue info

- src/content/pages/sprints.mdx
A proposal for a sprint about [pygount](https://pypi.org/project/pygount/).
> Add pygount sprint

- src/content/pages/sprints.mdx
> Nikas bracelet waving workshop

- src/content/pages/aitournament.mdx
Add the final scores for the participants and thanks to organisers that helped and sponsors that provided the prizes.
> Add results to aitournament.mdx

- src/components/keynoters/keynoter.astro
- src/components/keynoters/keynoters.astro
- src/content/config.ts
- src/content/keynoters/anna.mdx
- src/content/keynoters/armin-ronacher.mdx
- src/content/keynoters/carol-willing.mdx
- src/content/keynoters/mai-gimenez.mdx
- src/content/keynoters/tereza-iofciu.mdx
- src/content/keynoters/łukasz-langa.mdx
> Make keynoter containers clickable

- scripts/download-data.py
The program API is down. We need update-data script to use this data for now
> Replace with temporary url

- src/components/footer.astro
- src/content/deadlines/01_questionnaire.md
"Name" is a typo, compare https://www.europython-society.org/imprint/
> Fix EPS address

- src/content/pages/programme/selection.mdx
- src/content/pages/programme/tracks.mdx
- src/data/links.json
> EP2025 selection process description

- src/content/pages/faq.mdx
An initial FAQ page
TODO: add timeline
> Add FAQ page

- LICENSE
It was accidentally deleted during migration last year
> Readd License
