data/pages-content/finaid.md
=> fix typo in timeline

data/pages-content/faq.md, data/pages-content/finaid.md
It's no longer possible to apply for financial aid for EuroPython 2022. I've changed the finaid page on the website to reflect this. The last open financial aid form, for remote finaid, will be closed as soon as the website no longer links to it.
=> Mark all financial aid grants as closed

components/datetime.tsx, components/schedule/schedule.tsx, package-lock.json, package.json, pages/session/[slug].tsx, styles/main.css
This PR add local time in the schedule and sessions:
you can view it here: https://ep2022-git-feature-timezone-europython-society.vercel.app/schedule/2022-07-11
=> Show user timezone on schedule and session page

data/pages-content/mentored-sprint.md
I hope this is the `Mu` project you were referring to :)
=> Fix project Mu link in mentored sprint

components/clacks.tsx, components/meta.tsx, pages/index.tsx
Context: In the Terry Pratchett novel "Going Postal", a telegraph-style system known as "Clacks" was used to pass the name of a deceased character endlessly back and forth, keeping their memory alive. But where the book had "GNU John Dearheart" -- the prefix being a basic code to instruct clacksmen to pass on, not file, and return the message -- we add meta headers to our base template in a silent but appropriately geeky tribute and act of remembrance to those in our EuroPython family we have lost.
=> Add clacks of remembrance to our base template

components/button/button.stories.tsx, components/button/button.tsx, components/button/index.tsx, components/mdx.tsx, data/pages-content/_test.md
This is a non-clickable button - to denote that when we are ready, it will be a clickable link, changing to `<ButtonLink>`
=> Add non-clickable button component

data/sponsors.json
TODO: we'll need to change the URL to https://cloud.google.com/developers/europython  NOT Live until July 12, 2023
=> Add Google cloud to sponsors.json

data/links.json, data/pages-content/mentored-sprint.md
Information about Mentored Sprints - details like room and time are not announced yet and minor information is subjected to changes. But It's good to have it on the website and start inviting projects to join.
=> Adding Mentored Sprint

app/page.tsx, data/deadlines/02_finaid.md, data/deadlines/02_sponsorship.md, data/pages-content/faq.md, data/pages-content/finaid.md
I've added a few lines indicating that we are no longer accepting financial aid applications. I've also moved the privacy policy section into its own section, as it's no longer connected directly to a link to the form.
~~Note: Applications are not closed yet. The deadline is 21 May 2023 Anywhere On Earth, which translates to 22 May 2023 at 12:00 UTC (or 14:00 CEST). We should not merge this before then. I'll change the "draft" status to non-draft after the deadline has passed.~~
Edit: The deadline has passed, and the form is closed. I've marked this PR as ready for review.
=> Indicate that finaid applications are closed

data/pages-content/sprints.md
I figured out how to build pytorch for m1/m2 macs and have posted the instructions that I used
=> Doc: updated pytorch sprint doc

data/home/intro.md
After the deadline is passed for the call for contributors I think is ok to remove any references from the home page
=> Remove call for contributors link

src/content/pages/cfp.mdx, src/content/pages/tickets.mdx
Updates:
* Updates the CfP page as the call has now ended. The page is updated according to the https://ep2023.europython.eu/cfp/ feel free to review!
* Updated the refund date from 17th to 8th, following the same changes with the late birds. (moved 9 days earlier as the conference is 9 days earlier than last year).
=> Minor content updates

src/content/pages/sponsor.mdx
1. Update the google drive link for "Full list of Optional Extras (PDF)" button that was not in the correct version
2. Move brochure at the "Ready to become a sponsor and join us in Prague?" section
=> Fix sponsorship packages link and move brochure up

src/content/pages/programme.mdx, src/data/links.json, src/pages/posters.astro, src/pages/talks.astro, src/pages/tutorials.astro
This is a PoC of separate pages for the different types of sessions. Plus the overview of the whole Programme.
This is just meant to present an idea, and is not a final version. Both copy and the code will need updates before merging :)
=> PoC/WiP: create separate talks/tutorials/posters pages

src/pages/session/[slug].astro, src/pages/speaker/[slug].astro
=> Fix sourceless image tags

src/content/pages/capi.mdx
It's [pybind11](https://pybind11.readthedocs.io/en/stable/index.html) :)
=> C API summit: Fix typo in project name

src/data/links.json
Link to sprints was at the beginning of the events tab. But belongs to the end.
=> Multiday events belong to the end.

src/content/pages/sprints.mdx
=> sprints: fix link to sprints page source

src/styles/global.css
For https://github.com/EuroPython/website/issues/682.
The WCAG AA min contrast ratio is 4.5.
contrast ratio: 3.99:1 https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=FF0000
contrast ratio: 4.53:1 https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=EE0000
=> A11y: fix red button contrast

src/components/schedule/session.astro
For https://github.com/EuroPython/website/issues/682.
Use primary colour (dark blue #0409e7) for schedule table headers. The ratio on the advanced #D34847 background is 2.17:1: https://webaim.org/resources/contrastchecker/?fcolor=000000&bcolor=D34847
Use black as the foreground colour. The ratio on the advanced #D34847 background is 4.78:1 https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=FF0000
The other levels all remain above the WCAG AA min of 4.5:1.
=> A11y: use black for schedule header to fix contrast

src/components/card/card.astro
For https://github.com/EuroPython/website/issues/682.
The contrast ratio of white on pink is too low: 2.22: 1
Instead of white on pink, use white on read, like the other buttons on the front page. With https://github.com/EuroPython/website/pull/773, the ratio will be 4.53:1, above the WCAG AA minimum of 4.5.
=> A11y: fix card button contrast

src/content/pages/sprints.mdx
Tiny improvements.
The page also says that registration will open “soon” for people who don't have a conference ticket but the linked page (`/tickets`) doesn't have information about that yet.
=> Update sprints page

src/data/links.json
The current footer still points to the 2023 photos instead of the 2024 photos we have now.
=> Fix the footer link to point to the 2024 photos instead of 2023

src/content/pages/faq.mdx
The Timeline in the faq was lagging behind by a lot. This should be fixed now.
=> Updates to the timeline in the FAQ so that it contains milestones up to today.

src/components/footer.astro
"Name" is a typo, compare https://www.europython-society.org/imprint/
=> Fix EPS address
